package com.palmastro.app.ui

object TestTags {
    const val ONBOARDING_HAND_LEFT = "onboarding_hand_left"
    const val ONBOARDING_HAND_RIGHT = "onboarding_hand_right"
    const val ONBOARDING_BIRTHDAY_YEAR = "onboarding_birthday_year"
    const val ONBOARDING_BIRTHDAY_MONTH = "onboarding_birthday_month"
    const val ONBOARDING_BIRTHDAY_DAY = "onboarding_birthday_day"
    const val ONBOARDING_NEXT = "onboarding_next"
    const val ONBOARDING_CONFIRM = "onboarding_confirm"
    const val ONBOARDING_SKIP = "onboarding_skip"
    const val ONBOARDING_START = "onboarding_start"
    const val SCAN_CAPTURE_BUTTON = "scan_capture_button"
    const val SCAN_RETAKE_BUTTON = "scan_retake_button"
    const val SCAN_CAMERA_PREVIEW = "scan_camera_preview"
    const val SCAN_COACHING_HINT = "scan_coaching_hint"
    const val SCAN_HAND_OVERLAY = "scan_hand_overlay"
    const val RESULTS_SCAN_BUTTON = "results_scan_button"
    const val RESULTS_SETTINGS_BUTTON = "results_settings_button"
    const val RESULTS_SHARE_BUTTON = "results_share_button"
    const val RESULTS_HISTORY_BUTTON = "results_history_button"
    const val RESULTS_DOMAIN_CARD = "results_domain_card"
    const val DETAIL_BACK_BUTTON = "detail_back_button"
    const val DETAIL_SHARE_BUTTON = "detail_share_button"
    const val HISTORY_BACK_BUTTON = "history_back_button"
    const val HISTORY_MONTH_CARD = "history_month_card"
    const val SETTINGS_BACK_BUTTON = "settings_back_button"
    const val SETTINGS_DELETE_BUTTON = "settings_delete_button"
    const val SETTINGS_DELETE_CONFIRM = "settings_delete_confirm"
    const val SETTINGS_RETENTION_SWITCH = "settings_retention_switch"
}
